### ISSUE TITLE
Team data - small logos?

### ISSUE THREAD

**Issue by alexnoob** [domini7/Rosters#2]
Hi, do you intend adding small logos to your team data JSON? Would you need some help?

**Comment by domini7** [comment]
I would accept any pull request that adds them. At the moment, some of the primary logos are using what could be suitable for small logos. It may be a tedious amount of work to make everything proper...

**Comment by alexnoob** [comment]
Thanks, I'll give a try - it might take some time indeed :p

**Comment by alexnoob** [comment]
Also, I noticed some of the logos are much larger than needed, for instance https://i.ibb.co/n1wVTDd/wsc.png is 4.8 Mo. Don't you mind if I reduce the size of these logos? (without removing transparency or decreasing too much quality). It could be appreciated especially for smartphone users who don't rely on Wifi

**Comment by domini7** [comment]
Yes, that would be fine as long as they don't lose transparency
